inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4

Documentation:
  Enabled: false
Style/DateTime:
  Enabled: false
Performance/HashEachMethods:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/WordArray:
  Enabled: false
